FROM elixir:1.15-otp-25

# Set environment
ENV MIX_ENV=dev

# Install hex and rebar
RUN mix local.hex --force && \
  mix local.rebar --force
#     apk add build-base

WORKDIR /workspaces/core-services

COPY mix.exs .
COPY mix.lock .

# Get dependencies, compile
RUN mix do deps.get, deps.compile

COPY . .
